add spring-cloud-gateway charts
openinsight-proj/openinsight-helm-charts pull request #107
Opened 2023-04-25 03:54 UTC by Accelerator96

2023-04-25 05:07 UTC, panpan0000 commented on charts/opentelemetry-demo-lite/templates/spring-cloud-gateway.yaml
> +                memory: 512Mi
is 512MB enough?

2023-04-25 05:08 UTC, panpan0000 commented
good job

2023-04-25 05:20 UTC, panpan0000 commented
漏了东西?

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-demo:
- components: Additional property springCloudGateway is not allowed

helm.go:84: [debug] values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-demo:
- components: Additional property springCloudGateway is not allowed

```

2023-04-25 05:31 UTC, panpan0000 commented on charts/opentelemetry-demo-lite/values.yaml
> +        repository: ghcr.io/openinsight-proj/demo
镜像`ghcr.io/openinsight-proj/demo:6adde5369780c1be22f148e0790a080575827aee-springCloudGateway` 拉不到的

2023-04-25 05:32 UTC, panpan0000 requested changes
for above comments

2023-04-25 06:13 UTC, Accelerator96 commented on charts/opentelemetry-demo-lite/templates/spring-cloud-gateway.yaml
> +                memory: 512Mi
512m enough

2023-04-26 07:15 UTC, panpan0000 commented on charts/opentelemetry-demo-lite/templates/springCloudGateway/spring-cloud-gateway.yaml
> +      port: 18081
!! 上面应用暴露18080， 这里的svc却是18081

2023-04-27 03:37 UTC, JaredTan95 commented
@Accelerator96 pls update spring cloud gateway image with latest tag: https://github.com/openinsight-proj/opentelemetry-demo/actions/runs/4815719682/jobs/8574661938

2023-04-27 03:53 UTC, JaredTan95 approved these changes

2023-04-27 03:53 UTC, merged